# Generated by Django 2.1.5 on 2019-02-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190131_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monent',
            new_name='Moment',
        ),
    ]
